# Generated by Django 5.1 on 2024-08-24 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidadeNome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemNome', models.CharField(max_length=100)),
                ('dataInclusao', models.DateField(auto_now_add=True)),
                ('itemLocalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.localidade')),
            ],
        ),
    ]
